FROM fedora:32
 			
RUN dnf update -y && dnf upgrade -y && \
	dnf install -y \
	binutils time bzip2 gcc gcc-c++ gawk gettext flex ncurses-devel \
	zlib-devel zlib-static make patch unzip perl-ExtUtils-MakeMaker \
	glibc glibc-devel glibc-static sed intltool sharutils \
	python3 python3-distutils-extra xz-static re2c bash mc nano \
	rsync zsh git wget openssl-devel openssl which libtool && \
	dnf clean all

RUN useradd -m user && \
    echo 'user ALL=NOPASSWD: ALL' > /etc/sudoers.d/user

USER user
WORKDIR /home/user/ledex
