FROM alpine:edge

RUN apk upgrade --update && apk add asciidoc curl sed build-base abuild alpine-sdk zsh bash bc binutils bzip2 \
    cdrkit coreutils diffutils findutils flex g++ gawk gcc gettext git grep intltool \
    libxslt linux-headers make ncurses-dev patch perl python2-dev python3-dev py3-setuptools python3 \
    rsync tar unzip  util-linux wget zlib-dev

RUN adduser -D user && \
    ln -sf bash /bin/sh && \
    ln -sf bash /usr/bin/sh

USER user
WORKDIR /home/user
