FROM fedora:30

# ADD yum.repos.d /etc/yum.repos.d/
# perl-Parse-Yapp perl-XML-Parser perl-JSON
# @c-development @development-tools @development-libs \

RUN dnf upgrade -y && \
	dnf install -y \
	binutils time bzip2 gcc gcc-c++ gawk gettext ncurses-devel flex \
	make patch unzip sharutils intltool util-linux zlib-devel zlib-static \
	perl-ExtUtils-MakeMaker perl-Thread-Queue \
	glibc glibc-devel sed cpio diffstat mc zstd tig \
	zlib-static elfutils-libelf-devel gawk unzip file wget \
	python3 python3-distutils-extra nano systemtap-devel \
	rsync zsh git wget openssl-devel openssl which 'dnf-command(download)' && \
	dnf clean all

RUN useradd -m user && \
    echo 'user ALL=NOPASSWD: ALL' > /etc/sudoers.d/user

USER user
WORKDIR /home/user/ledex
