FROM i386/debian:testing-backports

# Install apt-fast to speed up downloading packages
ADD apt-fast/* /tmp/
RUN /tmp/install_apt-fast.sh

# Install basic utilities
RUN apt-fast update && apt-fast install -y time curl wget git ca-certificates

# Install build tools
RUN apt-fast update && \
    apt-fast upgrade -y && \
    apt-fast install -y build-essential g++ bash make patch gawk flex \
    			libncurses6 libncurses-dev zlib1g-dev rsync nano zsh re2c \
    			gettext unzip xz-utils python2 python3 python3-distutils-extra libbz2-dev \
    			libcurl4-gnutls-dev libreadline-dev libsqlite3-dev python-all apt-file && \
    apt-fast --purge autoremove -y

RUN /tmp/remove_apt-fast.sh

# Clean /tmp, cache of downloaded packages and apt-fast indexes
RUN rm /tmp/* && apt-fast clean && rm -rf /var/lib/apt/lists/*

# Add user as lede cannot be built as root
RUN useradd -m user

#    ln -sf bash /bin/sh && \
#    ln -sf bash /usr/bin/sh

# Add build.sh for building with ease
ADD build.sh /usr/local/bin/

USER user
WORKDIR /home/user
CMD ["/usr/local/bin/build.sh"]
