FROM fedora:30

#ADD yum.repos.d /etc/yum.repos.d/

RUN dnf upgrade -y && dnf install -y \
	binutils time bzip2 gcc gcc-c++ gawk gettext flex ncurses-devel \
	make patch unzip sharutils intltool util-linux zlib-devel zlib-static \
	perl-XML-Parser perl-ExtUtils-MakeMaker perl-Parse-Yapp perl-JSON perl-Thread-Queue \
	glibc glibc-devel glibc-static sed cpio diffstat mc zstd tig \
	python2 python3 python3-distutils-extra nano \
	rsync zsh git wget openssl-devel openssl which 'dnf-command(download)' && \
	dnf clean all

RUN useradd -m user && \
    echo 'user ALL=NOPASSWD: ALL' > /etc/sudoers.d/user

USER user
WORKDIR /home/user/ledex
