FROM i386/alpine:edge

RUN apk update && apk upgrade --update && \
    apk add build-base gcc g++ wget git curl sed abuild alpine-sdk bash bc \
    binutils bzip2 flex bison m4 autoconf automake libtool \
    coreutils diffutils findutils gawk gettext grep intltool ca-certificates \
    libxslt make patch perl python2-dev python3-dev py3-setuptools python3 bash \
    rsync tar unzip util-linux sudo zsh \
    libbsd-dev bzip2-dev bzip2-static zlib-dev readline-dev pcre-dev ncurses-dev sqlite-dev sqlite-static \
    libsodium-dev openssl-dev nano tig mc rust cargo

# ncurses-static bzip2-static zlib-static readline-static curl-static openssl-libs-static libssh2-static
# RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/v3.12/main zsh

RUN adduser -D user && \
    echo 'user ALL=NOPASSWD: ALL' > /etc/sudoers.d/user && \
    ln -sf bash /bin/sh && \
    ln -sf bash /usr/bin/sh

USER user
WORKDIR /home/user
